In [23]:
import numpy as np
from sympy import Matrix # Used to compute nullity

In [24]:
G = 'B' # Type of classical algebraic group, Input: string 'A','B','C', or 'D'
l = 2 # Rank, Input: positive integer
n = 2*l+1 # Square matrix dimension for type B

In [25]:
"""
Make matrices for the root vectors for the positive roots in type B (i.e., the root vectors in the nilradical).
Store the root vector matrices in a dictionary called rvecs where the keys are the eigenvector names given on page 131
of Erdmann and the values are the eigenvectors as numpy arrays

"mat_type" is the eigenvector matrix form given on page 131 of Erdmann
"indices" is a list of the i,j indices
"matrix" is the eigenvector corresponding to the root of specified type and indices
"coords" are the coordinates of the positive nonzero matrix entry, to be used for the coordinate function

Parameters: rank l

Returns: dictionary

"""
def make_rvecs_B(l):
    rvecs = {}

    M = np.zeros((2*l+1,2*l+1),dtype = int)
    # Add root vectors b_i for roots of the form epsilon_i to rvecs
    for i in np.arange(1,l+1,1):
        # b_ij
        M[i,0] = 1
        M[0,l+i] = -1
        hilo = "b" + str(i)
        coef = np.zeros(l, dtype = int) # Array of length the number of roots in the base
        coef[i-1:l] = 1
        coef = tuple(coef)
        rvecs.setdefault(coef, {"matrix":M, "coords":[i,0]}) # index 1 \leq i \leq l
        M = np.zeros((2*l+1,2*l+1),dtype = int)
    for i in np.arange(1,l,1):
        for j in np.arange(1,l+1,1):
            # p_ij
            if i<j:
                M[i,l+j] = 1
                M[j,l+i] = -1
                hilo = "p" + str(i) + str(j)
                coef = np.zeros(l, dtype = int) # Array of length the number of roots in the base
                coef[i-1:j] = 1
                coef[j-1:l] = 2
                coef = tuple(coef)
                rvecs.setdefault(coef, {"matrix":M, "coords":[i,l+j]}) # indices 1 \leq i < j \leq l
                M = np.zeros((2*l+1,2*l+1),dtype = int)
            # m_ij
            if i != j and i<j:
                M[i,j] = 1
                M[l+j,l+i] = -1
                hilo = "m" + str(i) + str(j)
                coef = np.zeros(l, dtype = int) # Array of length the number of roots in the base
                coef[i-1:j-1] = 1 
                coef = tuple(coef)
                rvecs.setdefault(coef, {"matrix":M, "coords":[i,j]})
                M = np.zeros((2*l+1,2*l+1), dtype = int)
    return rvecs

rvecs = make_rvecs_B(l)
print(rvecs)

{(1, 1): {'matrix': array([[ 0,  0,  0, -1,  0],
       [ 1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]]), 'coords': [1, 0]}, (0, 1): {'matrix': array([[ 0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]]), 'coords': [2, 0]}, (1, 2): {'matrix': array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1],
       [ 0,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]]), 'coords': [1, 4]}, (1, 0): {'matrix': array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0]]), 'coords': [1, 2]}}


In [26]:
"""
Fix a sequence of the positive roots with a (partial) ordering induced by increasing root height.

Use the Sage function positive_roots_by_height(increasing=True)

Parameters: Group type G, string
            Rank, integer

Returns: List of roots as tuples
"""
def make_root_order(G,l):
    L = RootSystem([G,l]).root_lattice()
    roots = [tuple(root.to_vector()) for root in L.positive_roots_by_height()]
    return roots

roots = make_root_order(G,l)
num_roots = len(roots) # Store the number of positive roots for future loops

In [54]:
"""
VERSION WHERE THE ENTRIES ARE THE DIFFERENT THAN THOSE IN THE NILRADICAL (r INSTEAD OF n)
Compute the root spaces $\mathfrak{g}_\beta=\mathbb{C}e_\beta$

Notes:
This could be combined with the function that makes the nilradical
The "DeprecationWarning: invalid escape sequence \m" that returns when this cell is run in Jupyter is because of the 
backslash character used in the TeX for this comment

Parameters: rvecs

Returns: rspaces: dictionary with keys the roots as tuples and values the root spaces
"""
def make_root_spaces(rvecs):
    rspaces = {} # Create a dictionary rspaces with keys the roots as stored in rvecs and values the root spaces k*e_alpha
    num = len(rvecs) # Set the number of iterations to equal the number of positive roots; we'll need this for most things in this function
    syms = np.array([var("r"+str(list(rvecs.keys())[i]).replace("(", "").replace(")", "").replace(" ", "").replace(",", "")) for i in range(num)], dtype = object) # Name some not-necessarily-distinct field elements
    # Note that rvecs[list(rvecs.keys())[1]]['matrix'] extracts the eigenvector matrix from rvecs
    mats = [np.dot(syms[i],rvecs[list(rvecs.keys())[i]]['matrix']) for i in range(num)] # Multiply the root vectors by an arbitrary field element to get the root spaces
    for i in range(num):
        rspaces.setdefault(list(rvecs.keys())[i],mats[i])
    return rspaces

rspaces = make_root_spaces(rvecs)

<>:13: DeprecationWarning: invalid escape sequence \m
<>:13: DeprecationWarning: invalid escape sequence \m
<>:13: DeprecationWarning: invalid escape sequence \m
<ipython-input-54-969feb4a3bad>:13: DeprecationWarning: invalid escape sequence \m
  """


In [28]:
"""
VERSION WHERE THE ENTRIES ARE THE SAME AS IN THE NILRADICAL
Compute the root spaces $\mathfrak{g}_\beta=\mathbb{C}e_\beta$

Notes:
This could be combined with the function that makes the nilradical
The "DeprecationWarning: invalid escape sequence \m" that returns when this cell is run in Jupyter is because of the 
backslash character used in the TeX for this comment

Parameters: rvecs

Returns: rspaces: dictionary with keys the roots as tuples and values the root spaces
"""
def make_root_spaces(rvecs):
    rspaces = {} # Create a dictionary rspaces with keys the roots as stored in rvecs and values the root spaces k*e_alpha
    num = len(rvecs) # Set the number of iterations to equal the number of positive roots; we'll need this for most things in this function
    syms = np.array([var("n"+str(list(rvecs.keys())[i]).replace("(", "").replace(")", "").replace(" ", "").replace(",", "")) for i in range(num)], dtype = object) # Name some not-necessarily-distinct field elements
    # Note that rvecs[list(rvecs.keys())[1]]['matrix'] extracts the eigenvector matrix from rvecs
    mats = [np.dot(syms[i],rvecs[list(rvecs.keys())[i]]['matrix']) for i in range(num)] # Multiply the root vectors by an arbitrary field element to get the root spaces
    for i in range(num):
        rspaces.setdefault(list(rvecs.keys())[i],mats[i])
    return rspaces

rspaces = make_root_spaces(rvecs)

<>:13: DeprecationWarning: invalid escape sequence \m
<>:13: DeprecationWarning: invalid escape sequence \m
<>:13: DeprecationWarning: invalid escape sequence \m
<ipython-input-28-6312676660ef>:13: DeprecationWarning: invalid escape sequence \m
  """


In [51]:
"""
Compute a matrix representing an arbitrary element of the nilradical

Input: rvecs
Returns: numpy.ndarray ; Arbitrary element of the nilradical
"""
def make_nilrad(rvecs):
    rspaces = {} # Create a dictionary rspaces with keys the roots as stored in rvecs and values the root spaces k*e_alpha
    
    num = len(rvecs) # Set the number of iterations to equal the number of positive roots; we'll need this for most things in this function
    syms = np.array([var("n"+str(list(rvecs.keys())[i]).replace("(", "").replace(")", "").replace(" ", "").replace(",", "")) for i in range(num)], dtype = object) # Name some not-necessarily-distinct field elements
    # Note that rvecs[list(rvecs.keys())[1]]['matrix'] extracts the eigenvector matrix from rvecs
    mats = [np.dot(syms[i],rvecs[list(rvecs.keys())[i]]['matrix']) for i in range(num)] # Multiply the root vectors by an arbitrary field element to get the root spaces
    nil_rad = sum(mats) # Set an arbitrary element of the nilradical equal to the sum of the root spaces
    
    for i in range(num):
        rspaces.setdefault(list(rvecs.keys())[i],mats[i])
    
    return nil_rad #,rspaces, mats

nil_rad = make_nilrad(rvecs)
nil_rad

array([[0, 0, 0, -n11, -n01],
       [n11, 0, n10, 0, n12],
       [n01, 0, 0, -n12, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, -n10, 0]], dtype=object)

In [30]:
"""
Compute the NT-submodules $\mathfrak{m}_i$
"""
def make_NT_submodules(n,roots,rspaces):
    mi_dict = {'m'+str(len(roots)): np.zeros((n,n), dtype = int)}
    for i in range(len(roots)):
        hilo = "m" + str(i)
        mi = rspaces[roots[i]]
        for k in range(i+1, len(roots)):
            mi += rspaces[roots[k]]
            #print(k,roots[k])

        mi_dict.setdefault(hilo,mi) #nil_rad-mi
    return mi_dict

mi_dict = make_NT_submodules(7,roots,rspaces)

<>:3: DeprecationWarning: invalid escape sequence \m
<>:3: DeprecationWarning: invalid escape sequence \m
<>:3: DeprecationWarning: invalid escape sequence \m
<ipython-input-30-e60e8b14dde7>:3: DeprecationWarning: invalid escape sequence \m
  """


In [31]:
mi_dict

{'m4': array([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]),
 'm0': array([[0, 0, 0, -n11, -n01],
        [n11, 0, n10, 0, n12],
        [n01, 0, 0, -n12, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, -n10, 0]], dtype=object),
 'm1': array([[0, 0, 0, -n11, 0],
        [n11, 0, n10, 0, n12],
        [0, 0, 0, -n12, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, -n10, 0]], dtype=object),
 'm2': array([[0, 0, 0, -n11, 0],
        [n11, 0, 0, 0, n12],
        [0, 0, 0, -n12, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=object),
 'm3': array([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, n12],
        [0, 0, 0, -n12, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=object)}

In [76]:
"""
Function to compute the alpha-string through beta for the bracket [x_alpha,x_beta] (given by q and r, see Humphreys p. 145)

Parameters: alpha: tuple 
    beta: tuple
    roots: list of roots as tuples
    
Returns: q,r : integers

"""
def get_rstring(alpha, beta, roots):
    #rstring_dict = {}
    gamma = beta
    q = 0
    print(gamma,type(gamma))
    while gamma in roots:
        gamma = tuple(np.add(gamma, alpha))
        if gamma in roots:
            q += 1
                
    gamma = beta
    r = 0
    while gamma in roots:
        gamma = tuple(np.subtract(gamma, alpha))
        if gamma in roots:
            r += 1
    return q,r

In [33]:
def Chev_bracket(alpha, beta, roots, rvecs):
    if alpha == beta:
        bracket = 0
    else:
        q, r = get_rstring(alpha,beta,roots)
        if q == 0:
            bracket = 0
        else:
            #print(rvecs[tuple(np.add(alpha,beta))]['matrix'])
            bracket = (r+1)*rvecs[tuple(np.add(alpha,beta))]['matrix'] #CHECK FOR SIGN CONVENTION
    return bracket

In [111]:
"""
Function to compute the dimension of the centralizer of x in u using the Chevalley commutator relations using the root vectors that were defined previously

define nil_coefs and vec_coefs as ORDERED DICTIONARIES where the keys are the roots and the values are the coefficients

Params: nil_coefs: list with the same order as roots of symbolic coefficient names nalpha1tuple etc. # ORDERED DICTIONARY where the keys are the roots and the values are the coefficients
    vec_coefs: ORDERED DICTIONARY where the keys are the roots and the values are the coefficients
    roots
    rvecs
    n (matrix dimension)

Returns: nullity
"""
def Chev_simp(nil_coefs, vec_coefs, roots, rvecs, n):
    mat = np.zeros((n,n),dtype = int)
    for alpha in roots: #nil_coefs: # nil_coefs.keys():
        for beta in vec_coefs: # .keys():
            #print(beta)
            bracket = Chev_bracket(alpha, beta, roots, rvecs)
            #print(bracket)
            a = nil_coefs[alpha]
            b = nil_coefs[beta]
            mat = np.add(mat, a*b*bracket)
            
    return mat

In [18]:
"""
Params: mat: matrix (numpy or probably some other kinds work too)

Returns: nullity: integer
"""

def nullity(mat):
    # Using Sympy      
    mat = Matrix(mat)
    NumCol = mat.shape[1]
    rank = mat.rank()
    # Nullity of the Matrix
    nullity = NumCol - rank
    
    return nullity

In [106]:
X[(1,0)] = 1
X

{(0, 1): 0, (1, 0): 1, (1, 1): 0, (1, 2): 0}

In [107]:
{key: value for key, value in X.items() if value != 0}

{(1, 0): 1}

In [114]:
def check_ramification():
    # Remove root vectors with coefficient zero from X
    vec_roots = {key: value for key, value in X.items() if value != 0}
    vec_coefs = vec_roots.values()
    mat = Chev_simp(nil_coefs, vec_coefs, roots, rvecs, n)
    mat = np.subtract(mat, mi_dict["m" + str(i)])
    if nullity(mat) == dimCu:
        print(str(i) + " is a ramification point")
        ramification = True
    elif nullity(mat) == dimCu - 1:
        print(str(i) + " is an inert point")
        dimCu = nullity(mat)
        ramification  = False
    else:
        print("something went wrong")
    return ramification, dimCu

In [113]:
X = dict(zip(roots, np.zeros(n, dtype = int))) # Initial X: Dictionary where the keys are root tuples and the values are zero
dimCu = n
nil_coefs = [var("n"+str(roots[i]).replace("(", "").replace(")", "").replace(" ", "").replace(",", "")) for i in range(len(roots))]
for i in range(1,len(roots)+1):
    # Remove root vectors with coefficient zero from X
    vec_roots = {key: value for key, value in X.items() if value != 0}
    vec_coefs = vec_roots.values()
    mat = Chev_simp(nil_coefs, vec_coefs, roots, rvecs, n)
    mat = np.subtract(mat, mi_dict["m" + str(i)])
    if nullity(mat) == dimCu:
        print(str(i) + " is a ramification point")
        ramification = True
    elif nullity(mat) == dimCu - 1:
        print(str(i) + " is an inert point")
        dimCu = nullity(mat)
        ramification  = False
    else:
        print("something went wrong")
    #nil_rad - mi_dict['m'+str(i)]
    
if ramification 

1 is a ramification point
2 is a ramification point
3 is a ramification point
4 is a ramification point


In [36]:
k = var('k')
Chev_simp({(0,1):k,(1,0):1,(1,1):1,(1,2):1},{(0,1):1,(1,0):0,(1,1):0,(1,2):0},roots,rvecs,n)

0
[[ 0  0  0 -1  0]
 [ 1  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
[[ 0  0  0  0  0]
 [ 0  0  0  0  2]
 [ 0  0  0 -2  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
0
[[ 0  0  0 -1  0]
 [ 1  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
0
0
0
[[ 0  0  0  0  0]
 [ 0  0  0  0  1]
 [ 0  0  0 -1  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
0
0
0
0
0
0
0


array([[0, 0, 0, -2*k, 0],
       [2*k, 0, 0, 0, 3*k],
       [0, 0, 0, -3*k, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=object)

In [123]:
nil_rad

array([[0, 0, 0, -n11, -n01],
       [n11, 0, n10, 0, n12],
       [n01, 0, 0, -n12, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, -n10, 0]], dtype=object)

In [129]:
"""
Calculation of U-orbits on u

"""
def make_row(previous_row_list, mi_dict):
    for i in range(len(roots)):
        mat = nil_rad - mi_dict['m'+str(i)]
        print(mat)
    

In [ ]:
X = 0


In [131]:
for i in range(1,len(roots)):
    print(i)

1
2
3


In [58]:
nil_coefs = [var("n"+str(roots[i]).replace("(", "").replace(")", "").replace(" ", "").replace(",", "")) for i in range(len(roots))]

In [63]:
X.values()

dict_values([0, 0, 0, 0])

In [53]:
np.array(var("n"+str(roots[i]).replace("(", "").replace(")", "").replace(" ", "").replace(",", "")))

array(n10, dtype=object)

In [55]:
rspaces

{(1,
  1): array([[0, 0, 0, -r11, 0],
        [r11, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=object),
 (0,
  1): array([[0, 0, 0, 0, -r01],
        [0, 0, 0, 0, 0],
        [r01, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=object),
 (1,
  2): array([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, r12],
        [0, 0, 0, -r12, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=object),
 (1,
  0): array([[0, 0, 0, 0, 0],
        [0, 0, r10, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, -r10, 0]], dtype=object)}

In [34]:
alpha = (0,1,1)
beta = (0,0,1)
brute = rvecs[tuple(alpha)]['matrix'] @ rvecs[tuple(beta)]['matrix'] - rvecs[tuple(beta)]['matrix'] @ rvecs[tuple(alpha)]['matrix']
test = Chev_bracket((0,1,1),(0,0,1),roots, rvecs)
print(brute)
print(test)

KeyError: (0, 1, 1)

In [53]:
"""
Function to compute the alpha-string through beta (given by q and r, see Humphreys p. 145)
(to be used in order to simplify a matrix using the Chevalley 
commutator relations using the root vectors that were defined previously)

define nil_coefs and vec_coefs as ORDERED DICTIONARIES where the keys are the roots and the values are the coefficients
"""

def get_rstring_old(nil_coefs, vec_coefs, roots):
    rstring_dict = {}
    for alpha in range(len(list(nil_coefs.keys()))):
        for beta in range(len(list(vec_coefs.keys()))):
            # Compute the alpha-string through beta (alpha i-string through alpha j)
            gamma = list(vec_coefs.keys())[beta]
            q = 0
            while gamma in roots:
                gamma = tuple(np.add(gamma, list(nil_coefs.keys())[alpha]))
                #print(str(list(nil_coefs.keys())[alpha])+str(list(vec_coefs.keys())[beta]),gamma)
                if gamma in roots:
                    q += 1
                
            gamma = list(vec_coefs.keys())[beta]
            r = 0
            while gamma in roots:
                gamma = tuple(np.subtract(gamma, list(nil_coefs.keys())[alpha]))
                if gamma in roots:
                    r += 1
            rstring_dict.setdefault(str(list(nil_coefs.keys())[alpha])+str(list(vec_coefs.keys())[beta]),{'q':q,'r':r})
            # Compute the bracket
            #XiXj = 
        return rstring_dict

In [ ]:
"""
Function to simplify a matrix using the Chevalley commutator relations using the root vectors that were defined previously

define nil_coefs and vec_coefs as DICTIONARIES
"""

In [68]:
"""
SCRATCH

Compute the NT-submodules $\mathfrak{m}_i$ as coordinates rather than matrices
"""
mi_dict = {}
for i in range(num_roots):
    hilo = "m" + str(i)
    mi = []
    mi.append(rvecs[roots[i]]['coords'])
    for k in range(i+1, num_roots):
        mi.append(rvecs[roots[k]]['coords'])
        #print(k,roots[k])
    
    mi_dict.setdefault(hilo,mi)
mi_dict

<>:3: DeprecationWarning: invalid escape sequence \m
<>:3: DeprecationWarning: invalid escape sequence \m
<>:3: DeprecationWarning: invalid escape sequence \m
<ipython-input-68-104dbd72c16d>:3: DeprecationWarning: invalid escape sequence \m
  """


{'m0': [[3, 0],
  [2, 3],
  [1, 2],
  [2, 0],
  [1, 3],
  [2, 6],
  [1, 0],
  [1, 6],
  [1, 5]],
 'm1': [[2, 3], [1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]],
 'm2': [[1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]],
 'm3': [[2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]],
 'm4': [[1, 3], [2, 6], [1, 0], [1, 6], [1, 5]],
 'm5': [[2, 6], [1, 0], [1, 6], [1, 5]],
 'm6': [[1, 0], [1, 6], [1, 5]],
 'm7': [[1, 6], [1, 5]],
 'm8': [[1, 5]]}

# Scratch

In [103]:
# SCRATCH
m_list = []
for level in range(num_roots):
    mat = nil_rad
    #print(mat)
    for rspace in range(len(mi_dict['m'+str(level)])):
        print(mi_dict['m'+str(level)])
        coords = mi_dict['m'+str(level)][rspace]
        print(coords)
        mat[coords[0],coords[1]] = 0
        m_list.append(mat)

[[3, 0], [2, 3], [1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]]
[3, 0]
[[3, 0], [2, 3], [1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]]
[2, 3]
[[3, 0], [2, 3], [1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]]
[1, 2]
[[3, 0], [2, 3], [1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]]
[2, 0]
[[3, 0], [2, 3], [1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]]
[1, 3]
[[3, 0], [2, 3], [1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]]
[2, 6]
[[3, 0], [2, 3], [1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]]
[1, 0]
[[3, 0], [2, 3], [1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]]
[1, 6]
[[3, 0], [2, 3], [1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]]
[1, 5]
[[2, 3], [1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]]
[2, 3]
[[2, 3], [1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]]
[1, 2]
[[2, 3], [1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]]
[2, 0]
[[2, 3], [1, 2], [2, 0], [1, 3], [2, 6], [1, 0], [1, 6], [1, 5]]

In [141]:
cand = nil_rad - mi_dict['m0']

for i in range(len(roots)):
    cand = nil_rad - mi_dict['m' + str(i)]
    # Check if i is an inert point or a ramification point
    bracket = nil_rad @ cand - cand @ nil_rad
    print(bracket)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 0 0 -n001*n110 -n001*n010 0]
 [n001*n110 0 0 0 0 0 -n001*n111]
 [n001*n010 0 0 0 0 0 -n001*n011]
 [0 0 0 0 n001*n111 n001*n011 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 0 0 -n001*n110 0 0]
 [n001*n110 0 0 n010*n100 0 -n010*n112 -n001*n111]
 [0 0 0 0 n010*n112 0 -n001*n011]
 [0 0 0 0 n001*n111 n001*n011 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 -n010*n100 0 0]]
[[0 0 0 0 n011*n100 - n001*n110 0 0]
 [-n011*n100 + n001*n110 0 0 0 0 -n010*n112 -n012*n100 - n001*n111]
 [0 0 0 0 n010*n112 0 -n001*n011]
 [0 0 0 0 n012*n100 + n001*n111 n001*n011 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 0 0 -n001*n110 0 0]
 [n001*n110 0 0 0 0 -n011*n111 - n010*n112 -n012*n100 - n001*n111]
 [0 0 0 0 n011*n111 + n010*n112 0 0]
 [0 0 0 0 n012*n100 + n001*n111 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 n01

In [145]:
list(rvecs.keys())[1]

(0, 1, 1)

In [162]:
mats[1]

array([[0, 0, 0, 0, 0, -n011, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [n011, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [169]:
(mats[0]+mats[1])@nil_rad-nil_rad@(mats[0]+mats[1])

array([[0, 0, 0, 0, n011*n100, 0, 0],
       [-n011*n100, 0, 0, 0, 0, 0, -n001*n111],
       [0, 0, 0, 0, 0, 0, -n001*n011],
       [0, 0, 0, 0, n001*n111, n001*n011, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [94]:
# Initialize vec_coefs as a numpy array with the greatest number of entries we could possibly need
# vec_coefs = np.zeros(len(roots),dtype = int)
# REWRITE THIS NOT TO USE APPEND
vec_roots = []
for key in X:
    if X[key] != 0:
        vec_roots.append(key)

vec_coefs

[(1, 0)]

In [144]:
nil_rad@rvecs[list(rvecs.keys())[1]]['matrix']-rvecs[list(rvecs.keys())[1]]['matrix']@nil_rad

array([[0, 0, 0, 0, -n4, 0, 0],
       [n4, 0, 0, 0, 0, -n0, 0],
       [0, 0, 0, 0, n0, 0, n2],
       [0, 0, 0, 0, 0, -n2, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [52]:
g = LieAlgebra(QQ, cartan_type=[G,l]) #, representation="matrix"

In [91]:
B3 = RootSystem(["B",3]).root_space()
roots=list(B3.positive_roots())
roots

[alpha[1],
 alpha[2],
 alpha[3],
 alpha[1] + alpha[2],
 alpha[2] + 2*alpha[3],
 alpha[2] + alpha[3],
 alpha[1] + alpha[2] + 2*alpha[3],
 alpha[1] + alpha[2] + alpha[3],
 alpha[1] + 2*alpha[2] + 2*alpha[3]]

In [53]:
g

Lie algebra of ['B', 3] in the Chevalley basis

In [19]:
g.lie_algebra_generators()

Finite family {alpha[1]: E[alpha[1]], alpha[2]: E[alpha[2]], alpha[3]: E[alpha[3]], -alpha[1]: E[-alpha[1]], -alpha[2]: E[-alpha[2]], -alpha[3]: E[-alpha[3]], alphacheck[1]: h1, alphacheck[2]: h2, alphacheck[3]: h3}

In [20]:
g.inject_variables()

Defining e1, e2, e3, f1, f2, f3, h1, h2, h3


In [94]:
print(e1)

E[alpha[1]]


In [67]:
n = LieAlgebra(QQ, cartan_type=['A',4], nilpotent=True)

In [ ]:
# Fix an enumeration of the positive roots s.t. ht(\beta_i)\leq ht(\beta_{i+1})



In [100]:
so4 = lie_algebras.so(QQ, 5, representation='matrix'); so4
so4.gens()

(
[ 0  1  0  0  0]  [ 0  0  0  0  0]  [ 0  0  0  0  0]  [ 0  0  0  0  0]
[ 0  0  0  0  0]  [ 0  0  0  0  2]  [ 1  0  0  0  0]  [ 0  0  0  0  0]
[ 0  0  0  0  0]  [ 0  0  0  0  0]  [ 0  0  0 -1  0]  [ 0  0  0  0  0]
[ 0  0 -1  0  0]  [ 0  0  0  0  0]  [ 0  0  0  0  0]  [ 0  0  0  0 -1]
[ 0  0  0  0  0], [ 0  0  0 -2  0], [ 0  0  0  0  0], [ 0  1  0  0  0],

[ 1  0  0  0  0]  [ 0  0  0  0  0]
[ 0 -1  0  0  0]  [ 0  2  0  0  0]
[ 0  0 -1  0  0]  [ 0  0  0  0  0]
[ 0  0  0  1  0]  [ 0  0  0 -2  0]
[ 0  0  0  0  0], [ 0  0  0  0  0]
)